### PR TITLE
Site updates

### PR DESCRIPTION
**Pull request by zprood**
## Done

[Update the content, applying the suggestions from last PR.]

### CODE REVIEW

**Comment by anasereijo** [comment]
Hi @zprood thanks for making the changes 👍 👍 

About Cloud index page what I was suggesting is instead of having that 451 Research image cropped (it wasn't designed to be like that) if you can simply make it as a background (check what [we did for the Takeover](https://github.com/canonical-websites/www.ubuntu.com/pull/3307)). See below:

screen shot 2018-06-13 at 17 47 46

**Comment by zprood** [comment]
@anasereijo Changed, the OpenStack logo is red, I think the dark background is a good choice, also inserted the image.

**Comment by anasereijo** [comment]
Hi @zprood thanks for making the changes but I was actually suggesting that background on the Cloud index page (/cloud/index/). As I said before that image wasn't desgined to be cropped like that. See below 

screen shot 2018-09-12 at 10 06 02

**Comment by zprood** [comment]
Sorry, misunderstand your point, will update soon.

**Comment by zprood** [comment]
@anasereijo Done.

**Comment by anasereijo** [comment]
Hi @zprood thanks for making the changes :)

It's looking much better but you kept the 451 research logo with the cropped background on the section below. Can you please remove it? I also don't think it makes sense repeating the e-book link twice.
here goes how I think it should look

screen shot 2018-09-12 at 13 47 59

Thank you

**Comment by zprood** [comment]
Hi @anasereijo , removed the 451 logo and link.

**Comment by zprood** [comment]
Hi @anasereijo, can you help to launch a demo, I have modified the Cloud/index section.

**Comment by anthonydillon** [comment]
@zprood why are you removing the logo?

**Comment by zprood** [comment]
Hi @anthonydillon, @anasereijo suggests me to remove it I think.

**Comment by anthonydillon** [comment]
@zprood @anasereijo is happy with it like it is now. Tidied up some of the code on a few pages. Good to go :+1:

**Comment by zprood** [comment]
@anthonydillon Thanks !

**Pull request merged**
