### PR TITLE
Update the navigation to match the latest design

### PR DESCRIPTION
**Pull request by anthonydillon**
## Done
Update the navigation to match the latest design

## QA
- Load the demo
- Check the navigation looks like https://www.ubuntu.com
- Check all the different screen sizes

## Issue / Card
FIxes https://github.com/canonical-websites/cn.ubuntu.com/issues/246

### CODE REVIEW

**Comment by anasereijo** [comment]
same comment as @zprood. everything else looks ok :) thanks

**Comment by anthonydillon** [comment]
@anasereijo @zprood Thanks, fixed the navigation width.

**Comment by anasereijo** [comment]
@Caleb-Ellis can you review this, please?
@Greggless there is no UX label but can you please have a look and QA it?

thank you ❤️

**Comment by Greggless** [comment]
# 🔥 🔥 🔥 

Most excellent. LGTM. 👍 

Now let's add the global nav 🙈

**Pull request merged**
