### PR TITLE
Merge pull request #186 from canonical-websites/master

### PR DESCRIPTION
**Pull request by zprood**
## Done
1. Fix the links
2. Update home page 
3. Update Contact Us page: /contact/index.html
4. add the contact us form under #3 page.

## QA
[N/A]
## Issue / Card
[N/A]

## Screenshots
Liamz's repo: https://github.com/zprood/newcnsite

### CODE REVIEW

**Comment by anthonydillon** [comment]
@zprood was this PR made by mistake? There doesn't seem to be any changes.

**Comment by zprood** [comment]
@anthonydillon I rised the PR, have update the broken links based on last update. Also update the old contact us page. Which channel V1 or master I need to create PR for?
Thanks.

**Comment by anthonydillon** [comment]
Thanks, @zprood but there are still no changes in the v1 branch from master. Did you create a branch on your fork of the site?

**Comment by zprood** [comment]
Hi Anthony, I fork the master branch to edit the site. I don't how to compare to branches, please forgive me.
You can see this two pages are not the same: 
**The orignal**: https://github.com/canonical-websites/cn.ubuntu.com/blob/master/templates/contact/index.html
**My version**: https://github.com/zprood/newcnsite/blob/master/templates/contact/index.html
I just have one branch in my repo.

**Comment by anthonydillon** [comment]
This has been superseded by #207

**Pull request closed without merging**
